# Generated by Django 2.2.10 on 2020-11-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('horario', models.CharField(max_length=80, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('aviso', models.TextField(blank=True, max_length=10000, null=True)),
                ('cookies', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgFondo', models.ImageField(upload_to='static/img')),
                ('textFondo', models.TextField(null=True)),
                ('textServicio', models.TextField(null=True)),
                ('imgServi1', models.ImageField(upload_to='static/img')),
                ('imgServi2', models.ImageField(upload_to='static/img')),
                ('proInicio', models.ImageField(upload_to='static/img')),
                ('textProfesional', models.TextField(null=True)),
            ],
        ),
    ]
