# Generated by Django 3.0.5 on 2020-09-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntradaBlog', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('descripcion', models.TextField(null=True)),
                ('fecha', models.DateTimeField()),
                ('imagen', models.ImageField(upload_to='static/img')),
                ('destacados', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('horario', models.CharField(max_length=80, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('aviso', models.TextField(blank=True, max_length=10000, null=True)),
                ('cookies', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgFondo', models.ImageField(upload_to='static/img')),
                ('textFondo', models.TextField(null=True)),
                ('textServicio', models.TextField(null=True)),
                ('imgServi1', models.ImageField(upload_to='static/img')),
                ('imgServi2', models.ImageField(upload_to='static/img')),
                ('proInicio', models.ImageField(upload_to='static/img')),
                ('textProfesional', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(null=True)),
                ('nombreServicio', models.CharField(max_length=80, null=True)),
                ('imagen', models.ImageField(upload_to='static/img')),
                ('CodigoF', models.ManyToManyField(to='app.CodigoPostal')),
            ],
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, null=True)),
                ('valoracion', models.IntegerField(null=True)),
                ('disponibilidad', models.TextField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(upload_to='static/img')),
                ('nombreServicio', models.ManyToManyField(to='app.Servicio')),
            ],
        ),
    ]
