# Generated by Django 3.0.5 on 2020-09-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='CodigoF',
        ),
        migrations.AddField(
            model_name='profesionales',
            name='CodigoF',
            field=models.ManyToManyField(to='app.CodigoPostal'),
        ),
    ]
