# Generated by Django 3.0.5 on 2020-10-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entradablog_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=80, null=True)),
                ('imagen', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
