# Generated by Django 2.2.11 on 2020-08-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entradablog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgFondo', models.ImageField(upload_to='static/img')),
                ('textFondo', models.TextField(null=True)),
                ('dscrServicio', models.TextField(null=True)),
                ('imgServi', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
