# Generated by Django 3.0.5 on 2020-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200928_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionales',
            name='nombreServicio',
        ),
        migrations.AddField(
            model_name='profesionales',
            name='nombreEspecialidad',
            field=models.ManyToManyField(to='app.Especialidades'),
        ),
    ]
