# Generated by Django 2.2.10 on 2020-11-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_codigopostal_precio_puntuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conocenos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conocenos', models.CharField(blank=True, max_length=50, null=True)),
                ('texto', models.TextField(max_length=10000, null=True)),
                ('imagenLogo', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='static/img')),
                ('nomImgGaleria', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, null=True)),
                ('disponibilidad', models.TextField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(upload_to='static/img')),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('PerfilGaleria1', models.ImageField(blank=True, upload_to='static/img')),
                ('PerfilGaleria2', models.ImageField(blank=True, upload_to='static/img')),
                ('PerfilGaleria3', models.ImageField(blank=True, upload_to='static/img')),
                ('PerfilGaleria4', models.ImageField(blank=True, upload_to='static/img')),
                ('CodigoPostales', models.ManyToManyField(related_name='profesionales', to='app.CodigoPostal')),
                ('nombreEspecialidades', models.ManyToManyField(to='app.Especialidades')),
                ('precioEspecialidades', models.ManyToManyField(to='app.Precio')),
                ('valoraciones', models.ManyToManyField(to='app.Puntuacion')),
            ],
        ),
    ]
