# Generated by Django 2.2.11 on 2020-08-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inicio',
            old_name='imgServi',
            new_name='imgServi1',
        ),
        migrations.AddField(
            model_name='inicio',
            name='imgServi2',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
