# Generated by Django 3.0.5 on 2020-10-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEspecialidad', models.CharField(max_length=80, null=True)),
                ('servicio', models.ForeignKey(max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad', to='app.Servicio')),
            ],
        ),
    ]
