# Generated by Django 3.0.5 on 2020-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200928_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidades',
            name='precio',
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(null=True)),
                ('nombreEspecialidad', models.ManyToManyField(to='app.Especialidades')),
            ],
        ),
    ]
