# Generated by Django 2.2 on 2020-11-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_conocenos_galeria_profesionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidades',
            name='imagen',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
