# Generated by Django 2.2 on 2020-12-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_especialidades_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='telefono',
            field=models.URLField(blank=True, null=True),
        ),
    ]
