# Generated by Django 2.2.10 on 2020-08-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200827_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='textProfesional',
            field=models.TextField(null=True),
        ),
    ]
