# Generated by Django 3.0.5 on 2020-10-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, null=True)),
                ('valoracion', models.IntegerField(null=True)),
                ('disponibilidad', models.TextField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(upload_to='static/img')),
                ('CodigoPostales', models.ManyToManyField(related_name='profesionales', to='app.CodigoPostal')),
                ('nombreEspecialidades', models.ManyToManyField(to='app.Especialidades')),
                ('precioEspecialidades', models.ManyToManyField(to='app.Precio')),
            ],
        ),
    ]
