# Generated by Django 3.0.5 on 2020-09-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profesionales_precioespecialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionales',
            name='CodigoF',
        ),
        migrations.AddField(
            model_name='codigopostal',
            name='CodigoF',
            field=models.ManyToManyField(to='app.Profesionales'),
        ),
    ]
