# Generated by Django 3.0.5 on 2020-10-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profesionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conocenos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=10000, null=True)),
                ('imagenLogo', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
