# Generated by Django 3.0.5 on 2020-09-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200929_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigopostal',
            name='CodigoF',
        ),
        migrations.AddField(
            model_name='profesionales',
            name='CodigoF',
            field=models.ManyToManyField(to='app.CodigoPostal'),
        ),
    ]
