# Generated by Django 2.2.10 on 2020-09-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='aviso',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='cookies',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
