# Generated by Django 2.2 on 2020-12-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201202_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionales',
            name='ServicioPrincipal',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
