# Generated by Django 2.2.11 on 2020-09-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200901_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peluqueros',
            name='textoPerfil',
        ),
        migrations.AddField(
            model_name='peluqueros',
            name='disponibilidad',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='peluqueros',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='peluqueros',
            name='valoracion',
            field=models.IntegerField(null=True),
        ),
    ]
