# Generated by Django 3.0.5 on 2020-09-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200929_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesionales',
            old_name='nombreEspecialidad',
            new_name='nombreEspecialidades',
        ),
        migrations.RenameField(
            model_name='profesionales',
            old_name='precioEspecialidad',
            new_name='precioEspecialidades',
        ),
        migrations.RemoveField(
            model_name='profesionales',
            name='CodigoF',
        ),
        migrations.AddField(
            model_name='profesionales',
            name='CodigoPostales',
            field=models.ManyToManyField(to='app.CodigoPostal', verbose_name='CodigoPostal'),
        ),
    ]
