# Generated by Django 2.2 on 2020-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profesionales_servicioprincipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='ServicioPrincipal',
            field=models.TextField(max_length=80, null=True),
        ),
    ]
