# Generated by Django 2.2.10 on 2020-12-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201203_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='nombreEspecialidad',
        ),
        migrations.RemoveField(
            model_name='profesionales',
            name='precioEspecialidades',
        ),
        migrations.AddField(
            model_name='especialidades',
            name='precio',
            field=models.ForeignKey(max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Precio'),
        ),
    ]
