# Generated by Django 3.0.5 on 2020-10-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_conocenos_conocenos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('imagen', models.ImageField(default='colaboradores/profile.png', upload_to='colaboradores')),
            ],
        ),
    ]
