# Generated by Django 2.2.10 on 2020-12-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201204_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionales',
            name='ServicioPrincipal',
        ),
    ]
