# Generated by Django 3.0.5 on 2020-09-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200930_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionales',
            name='CodigoPostales',
        ),
        migrations.AddField(
            model_name='codigopostal',
            name='profesionales',
            field=models.ManyToManyField(to='app.Profesionales', verbose_name='profesional'),
        ),
    ]
