# Generated by Django 2.2 on 2020-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_colaboradores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='static/img')),
                ('nomImgGaleria', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='imagen',
            field=models.ImageField(default='colaborador/profile.png', upload_to='colaborador'),
        ),
    ]
