# Generated by Django 2.2 on 2020-10-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201017_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='descripcionpag',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='tituloPag',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
