# Generated by Django 2.2 on 2020-12-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_profesionales_servicioprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionales',
            name='nombreServicio',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
