# Generated by Django 3.0.5 on 2020-09-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_peluqueros_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peluqueros',
            name='disponibilidad',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
