# Generated by Django 3.0.5 on 2020-09-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200930_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigopostal',
            name='profesionales',
        ),
        migrations.AddField(
            model_name='profesionales',
            name='CodigoPostales',
            field=models.ManyToManyField(to='app.CodigoPostal', verbose_name='codigospostal'),
        ),
    ]
