# Generated by Django 2.2 on 2020-10-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201017_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='descripcionpag',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='tituloPag',
        ),
    ]
