# Generated by Django 3.0.5 on 2020-09-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200908_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, null=True)),
                ('peluquero', models.ManyToManyField(to='app.Peluqueros')),
            ],
        ),
    ]
