# Generated by Django 3.0.5 on 2020-09-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200930_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='CodigoPostales',
            field=models.ManyToManyField(to='app.CodigoPostal', verbose_name='profesionales'),
        ),
    ]
