# Generated by Django 2.2.10 on 2020-12-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profesionales_nombreservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionales',
            name='nombreServicio',
        ),
    ]
