# Generated by Django 2.2 on 2020-10-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201022_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='imagen',
            new_name='imagenColumna1',
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagenColumna2',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagenColumna3',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
