# Generated by Django 2.2.10 on 2020-12-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_profesionales_nombreservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionales',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
