# Generated by Django 3.0.5 on 2020-10-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
