# Generated by Django 3.0.5 on 2020-09-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200930_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='CodigoPostales',
            field=models.ManyToManyField(related_name='profesionales', to='app.CodigoPostal'),
        ),
    ]
