# Generated by Django 2.2.10 on 2020-12-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_profesionales_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='descripcion',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
