# Generated by Django 2.2 on 2020-10-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201022_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='imagenColumna1',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='imagenColumna2',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='imagenColumna3',
        ),
    ]
