# Generated by Django 2.2 on 2020-10-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201027_1808'),
        ('app', '0015_auto_20201022_1814'),
    ]

    operations = [
    ]
