# Generated by Django 3.0.5 on 2021-01-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201219_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradablog',
            options={'ordering': ['fecha']},
        ),
    ]
