# Generated by Django 2.2.11 on 2020-09-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_servicio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(null=True)),
                ('profesionalCP', models.ManyToManyField(to='app.Peluqueros')),
            ],
        ),
    ]
