# Generated by Django 3.0.5 on 2021-01-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210113_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradablog',
            options={},
        ),
    ]
