# Generated by Django 3.0.5 on 2020-10-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201029_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaboradores',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
