# Generated by Django 2.2.11 on 2020-09-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_codigopostal'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigopostal',
            name='peluqueroCP',
            field=models.ManyToManyField(to='app.Servicio'),
        ),
    ]
