# Generated by Django 2.2.10 on 2020-10-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201030_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionales',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profesionales',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
