# Generated by Django 3.0.5 on 2021-01-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210125_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradablog',
            options={'ordering': ['-fecha']},
        ),
    ]
