# Generated by Django 3.0.5 on 2020-11-03 11:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201103_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='CodigoPostales',
            field=models.ManyToManyField(limit_choices_to=app.models.CodigoPostal, related_name='profesionales', to='app.CodigoPostal'),
        ),
    ]
