# Generated by Django 2.2.10 on 2020-10-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201030_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionales',
            name='PerfilGaleria1',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='profesionales',
            name='PerfilGaleria2',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='profesionales',
            name='PerfilGaleria3',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='profesionales',
            name='PerfilGaleria4',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
