# Generated by Django 3.0.5 on 2020-11-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201103_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='CodigoPostales',
            field=models.ManyToManyField(related_name='profesionales', to='app.CodigoPostal'),
        ),
    ]
