# Generated by Django 2.2.11 on 2020-09-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200922_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigopostal',
            name='profesionalCP',
            field=models.ManyToManyField(to='app.Peluqueros'),
        ),
        migrations.AddField(
            model_name='codigopostal',
            name='servicioCP',
            field=models.ManyToManyField(to='app.Servicio'),
        ),
        migrations.AlterField(
            model_name='codigopostal',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
    ]
