# Generated by Django 3.0.5 on 2020-11-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201103_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionales',
            name='puntuacion_fk',
            field=models.ManyToManyField(to='app.Valoracion'),
        ),
    ]
