# Generated by Django 2.2.11 on 2020-09-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200922_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigopostal',
            name='profesionalCP',
        ),
        migrations.RemoveField(
            model_name='codigopostal',
            name='servicioCP',
        ),
        migrations.RemoveField(
            model_name='peluqueros',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='peluquero',
        ),
        migrations.AddField(
            model_name='peluqueros',
            name='CodigoFK',
            field=models.ManyToManyField(to='app.CodigoPostal'),
        ),
        migrations.AddField(
            model_name='peluqueros',
            name='nombreServicio',
            field=models.ManyToManyField(to='app.Servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
