# Generated by Django 3.0.5 on 2020-11-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_profesionales_puntuacion_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='puntuacion_fk',
            field=models.ManyToManyField(related_name='profesionales', to='app.Valoracion'),
        ),
    ]
