# Generated by Django 2.2.11 on 2020-09-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200922_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peluqueros',
            new_name='Profesionales',
        ),
    ]
