# Generated by Django 2.2.10 on 2020-11-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201030_1320'),
        ('app', '0024_auto_20201103_1306'),
    ]

    operations = [
    ]
