# Generated by Django 2.2.10 on 2020-11-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_merge_20201105_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionales',
            name='puntuacion_fk',
        ),
        migrations.DeleteModel(
            name='Valoracion',
        ),
    ]
