# Generated by Django 2.2.10 on 2020-11-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20201105_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesionales',
            old_name='valoracion',
            new_name='valoraciones',
        ),
    ]
