# Generated by Django 3.0.5 on 2020-10-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
